name: |-
  Hotfix workflow enable
  
  For each new release create `release/{version}` branch that is key puzzle for `hotfix` workflow.
  
  ### Usage 
  
  Create in your repo  __`.github/workflows/eks-argocd-hotfix-enabled.yaml`__
  
  ```yaml
    name: Release branch
    on:
      release:
        types: [published]
  
    permissions:
      id-token: write
      contents: write
  
    jobs:
      hotfix:
        name: release / branch
        uses: ./.github/workflows/eks-argocd-hotfix-mixin.yml
        with:
          version: $\{\{ github.event.release.tag_name \}\}
  ```
  
  or add `hotfix` job to existing __`.github/workflows/release.yaml`__
  
  ```
    jobs:
      hotfix:
        name: release / branch
        uses: ./.github/workflows/eks-argocd-hotfix-mixin.yml
        with:
          version: $\{\{ github.event.release.tag_name \}\}  
  ```

on:
  workflow_call:
    inputs:
      version:
        description: "Release version tag"
        required: true
        type: string

permissions:
  id-token: write
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  create:
    uses: ./.github/workflows/workflow-controller-hotfix-release-branch.yml
    with:
      version: ${{ inputs.version }}
