name: Main Branch
on:
  push:
    branches: 
      - master
      - main

permissions:
  contents: write
  id-token: write

jobs:
  do:
    uses: ./.github/workflows/eks-argocd-main-branch.yml
    with:
      organization: "${{ github.event.repository.owner.login }}"
      repository: "${{ github.event.repository.name }}"
      path: deploy
      tests_enabled: false
    secrets:
      github-private-actions-pat: "${{ secrets.ARGOCD_GITHUB_NONPROD }}"
      registry: "${{ secrets.ECR_REGISTRY }}"
      secret-outputs-passphrase: "${{ secrets.GHA_SECRET_OUTPUT_PASSPHRASE }}"
      ecr-region: "${{ secrets.ECR_REGION }}"
      ecr-iam-role: "${{ secrets.ECR_IAM_ROLE }}"
