name: |-
  Controller - Draft release
  
  Create or update draft release

  ### Usage 

  ```yaml
    name: Draft release
    on:
      push:
        branches: [ main ]

    jobs:
      do:
        uses:  ./.github/workflows/workflow-controller-draft-release.yml@main
        with:
          ref: $\{\{ github.sha \}\}

  ```

on:
  workflow_call:
    inputs:
      ref:
        description: "The release target, i.e. branch or commit it should point to"
        required: false
        default: ${{ github.sha }}
        type: string

jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Create/Update Draft release
        uses: release-drafter/release-drafter@v5
        with:
          publish: false
          prerelease: false
          config-name: configs/draft-release.yml
          commitish: ${{ inputs.ref }}
