name: |-
  Controller - Draft release
  
  Create or update draft release

  ### Usage 

  ```yaml
    name: Draft release
    on:
      push:
        branches: [ main ]

    jobs:
      do:
        uses:  cloudposse/github-actions-workflows/.github/workflows/controller-draft-release.yml@main
        with:
          ref: $\{\{ github.sha \}\}
        secrets:
          github-private-actions-pat: $\{\{ secrets.github-private-actions-pat \}\}

  ```

on:
  workflow_call:
    inputs:
      ref:
        description: "The release target, i.e. branch or commit it should point to"
        required: false
        default: ${{ github.sha }}
        type: string

    secrets:
      github-private-actions-pat:
        description: "Github PAT allow to create release"
        required: true
jobs:
  draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Create/Update Draft release
        uses: release-drafter/release-drafter@v5
        with:
          publish: false
          prerelease: false
          config-name: configs/draft-release.yml
          commitish: ${{ inputs.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-private-actions-pat }}
